name: Database Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify MySQL Connection
        run: |
          sudo apt-get install -y mysql-client
          mysql --host=127.0.0.1 --port=3306 -uroot -p${{ secrets.DB_PASSWORD }} -e "SHOW DATABASES;"

      - name: Load Test Data (Optional)
        run: |
          mysql --host=127.0.0.1 --port=3306 -uroot -p${{ secrets.DB_PASSWORD }} test_db < chinook.sql

      - name: Configure Environment Variables
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_DRIVER=${{ secrets.DB_DRIVER }}" >> $GITHUB_ENV

      - name: Build and Run Tests
        run: mvn clean test
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DRIVER: ${{ secrets.DB_DRIVER }}
